shiro:
    # 登录提交信息加密（如果不需要加密，设置为空即可）
    loginSubmit:
         # 加密用户名、密码、验证码，后再提交（key设置为3个，用逗号分隔）加密方式：DES（4.1.9及之前版本默认设置）
         # v4.2.0+ 开始支持 Base64 加密方式，方便移动端及第三方系统处理认证，可直接设置 Key 为 Base64（4.2.0+默认设置）
         #secretKey: thinkgem,jeesite,com
         secretKey: NabobBase64
         #secretKey: ~

    # 记住我密钥设置，你可以通过 com.jeesite.test.RememberMeKeyGen 类快速生成一个秘钥。
    # 若不设置，则每次启动系统后自动生成一个新秘钥，这样会导致每次重启后，客户端记录的用户信息将失效。
    #rememberMe:
      #secretKey: ~

    # 允许的请求方法设定，解决安全审计问题
    allowRequestMethods: GET,POST,OPTIONS,PUT,DELETE

    # 是否允许账号多地登录，如果设置为false，同一个设备类型的其它地点登录的相同账号被踢下线
    isAllowMultiAddrLogin: true

    # 是否允许多账号多设备登录，如果设置为false，其它地点登录的相同账号全部登录设备将被踢下线
    isAllowMultiDeviceLogin: true

    # 是否允许刷新主框架页，如果设置为false，刷新主页将导致重新登录。如安全性比较高的，如银行个人首页不允许刷新。
    isAllowRefreshIndex: true

    # 是否允许嵌入到外部网站iframe中（true：不限制，false：不允许）
    isAllowExternalSiteIframe: true

    # 是否允许跨域访问 CORS，如果允许，设置允许的域名，全部域名设置*号，如果不允许，此设置应该为空
    #accessControlAllowOrigin: http://demo.jeesite.com
    accessControlAllowOrigin: "*"

    # 允许跨域访问时 CORS，可以使用的方法和标头
    accessControlAllowMethods: GET, POST, OPTIONS
    accessControlAllowHeaders: Origin, No-Cache, X-Requested-With, If-Modified-Since, Pragma, Last-Modified, Cache-Control, Expires, Content-Type, X-E4M-With

    # 是否允许接收跨域的Cookie凭证数据 CORS
    accessControlAllowCredentials: true

    # 允许的网站来源地址，不设置为全部地址（避免一些跨站点请求伪造 CSRF、防盗链）
    #  allowReferers: http://127.0.0.1,http://localhost
    allowReferers: ~

    # 是否在登录后生成新的Session（默认false）
    isGenerateNewSessionAfterLogin: false

# Web 相关
web:
  # MVC 视图相关
  view:
    # 使用 .json、.xml 后缀匹配视图（不推荐使用，推荐使用 favorParameter） v4.2.0
    favorPathExtension: false
    # 使用 __ajax=json、__ajax=xml 参数名匹配视图  v4.2.0
    favorParameter: true
